USE MASTER
GO

CREATE DATABASE FARMACIA2017
GO

USE FARMACIA2017
GO


CREATE TABLE PRINCIPIO_ACTIVO
(
ID_PA INT PRIMARY KEY IDENTITY(1,1) ,
DESCRIPCION VARCHAR(70) NOT NULL,
CATEGORIA VARCHAR(12) NOT NULL ,--MONOFARMACO - POLIFARMACO
ESTADO CHAR(1) DEFAULT 'A'
)
GO

 INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION, CATEGORIA) VALUES('paracetamol','monofarmaco');
 INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION, CATEGORIA) VALUES('abacavir','monofarmaco');
 
 

select * from PRODUCTO


update PRODUCTO set STOCK=100 


CREATE TABLE LABORATORIO
(
ID_LAB INT PRIMARY KEY IDENTITY(1,1),
RAZON_SOCIAL VARCHAR(70) NOT NULL,
UBICACION VARCHAR(45) ,
TELEFONO VARCHAR(20),
HORA_ATENCION VARCHAR(45),
DIRECTOR VARCHAR(45),
ESTADO CHAR(1) DEFAULT 'A'
)
GO

INSERT INTO LABORATORIO(RAZON_SOCIAL) VALUES('GSK')
INSERT INTO LABORATORIO(RAZON_SOCIAL) VALUES('EUROFARMA PERU')
INSERT INTO LABORATORIO(RAZON_SOCIAL) VALUES('FARMINDUSTRIA')
INSERT INTO LABORATORIO(RAZON_SOCIAL) VALUES('IQ FARMA')
GO

CREATE PROCEDURE USP_REGISTRAR_LABORATORIO
@RAZON_SOCIAL VARCHAR(70),
@UBICACION VARCHAR(45) ,
@TELEFONO VARCHAR(20),
@HORA_ATENCION VARCHAR(45),
@DIRECTOR VARCHAR(45)
AS
INSERT INTO LABORATORIO(RAZON_SOCIAL,UBICACION,TELEFONO,HORA_ATENCION,DIRECTOR) VALUES (@RAZON_SOCIAL,@UBICACION,@TELEFONO,@HORA_ATENCION,@DIRECTOR)
GO

select  ID_LAB,  RAZON_SOCIAL, DIRECTOR from LABORATORIO








CREATE TABLE PRESENTACION_PRODUCTO
(
ID_PP INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(70) NOT NULL,
ESTADO CHAR(1) DEFAULT 'A'
)
GO

INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION) VALUES('CAJA');
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION) VALUES('AMPOLLA');
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION) VALUES('TABLETA');




CREATE TABLE TIPO_PRODUCTO
(
ID_TPROD INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(45) NOT NULL,
ESTADO CHAR(1) DEFAULT 'A'
)
GO

INSERT INTO TIPO_PRODUCTO(DESCRIPCION) VALUES('HIGIENE PERSONAL');
INSERT INTO TIPO_PRODUCTO(DESCRIPCION) VALUES('MEDICAMENTOS');
INSERT INTO TIPO_PRODUCTO(DESCRIPCION) VALUES('BELLEZA');
INSERT INTO TIPO_PRODUCTO(DESCRIPCION) VALUES('OTROS');
GO


CREATE TABLE PRODUCTO
(
ID_PROD INT PRIMARY KEY IDENTITY (100,1),
ID_TPROD INT FOREIGN KEY REFERENCES TIPO_PRODUCTO(ID_TPROD),
ID_PP INT FOREIGN KEY REFERENCES PRESENTACION_PRODUCTO(ID_PP) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
STOCK INT NOT NULL ,
DESCRIPCION VARCHAR(100)  NULL,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
ESTADO CHAR(1) DEFAULT 'A'
)
GO

CREATE TABLE DETALLE_MEDICAMENTO
(
ID_DM INT PRIMARY KEY IDENTITY(1,1),
ID_PROD INT FOREIGN KEY REFERENCES PRODUCTO(ID_PROD) NOT NULL,
ID_PA INT FOREIGN KEY REFERENCES PRINCIPIO_ACTIVO(ID_PA) NOT NULL,
ID_LAB INT FOREIGN KEY REFERENCES LABORATORIO(ID_LAB) NOT NULL,
NRO_LOTE  VARCHAR(20) NOT NULL,
FECHA_VENCIMIENTO DATETIME NOT NULL,
CONDICION_VENTA VARCHAR(45) NOT NULL , -- CON RECETA MEDICA // SIN RECETA MEDICA //  CON RECETA MEDICA RETENIDA
TIPO_MEDICAMENTO VARCHAR(45) NOT NULL , -- GENERICO  // DE MARCA 
)
GO


CREATE TABLE TIPO_USUARIO(
ID_TPUS INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(30) NOT NULL,
ESTADO CHAR(1) DEFAULT 'A'
)
GO

INSERT INTO TIPO_USUARIO(DESCRIPCION)  VALUES('ADMINISTRADOR');
INSERT INTO TIPO_USUARIO(DESCRIPCION)  VALUES('TECNICO FARMACEUTICO');

SELECT * FROM TIPO_USUARIO
GO

CREATE TABLE USUARIO
(
ID_USUARIO INT  PRIMARY KEY IDENTITY(100,1),
USERNAME VARCHAR(20) NOT NULL,
XPASSWORD VARCHAR(45) COLLATE Latin1_General_CS_AS NOT NULL,
ID_TPUS INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID_TPUS) NOT NULL,
DESCRIPCION VARCHAR(45) NOT NULL,
FECHAALTA DATETIME DEFAULT  GETDATE(),
FECHABAJA DATETIME ,
ESTADO CHAR(1) DEFAULT 'A'
)
GO
INSERT INTO USUARIO(USERNAME,XPASSWORD,ID_TPUS,DESCRIPCION) VALUES('CAJERO1','CAJERO1','2','CAJERO DEL ESTABLECIMIENTO');
INSERT INTO USUARIO(USERNAME,XPASSWORD,ID_TPUS,DESCRIPCION) VALUES('admin','2119e2e075568b108bf3eafcc6ea0a4a','1','ADMINISTRADOR  / GERENTE');

select * from USUARIO


CREATE TABLE VENTA(
ID_VENTA INT PRIMARY KEY IDENTITY(1,1) ,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID_USUARIO),
FECHAPEDIDO DATETIME DEFAULT  GETDATE(),
ESTADO CHAR(1)
)

CREATE TABLE DETALLE_VENTA
(
ID_DETVENTA INT PRIMARY KEY IDENTITY(10,1),
ID_VENTA INT FOREIGN KEY REFERENCES VENTA(ID_VENTA) NOT NULL,
ID_PROD INT FOREIGN KEY REFERENCES PRODUCTO(ID_PROD) NOT NULL ,
CANTIDAD INT  NOT NULL,
DESCUENTO DECIMAL(10,2) NOT NULL
)
GO


CREATE PROCEDURE SP_REGISTRAR_PRODUCTO
@ID_TPROD INT ,
@ID_PP INT  ,
@NOMBRE VARCHAR(100) ,
@PRECIO_UNI DECIMAL(10,2),
@STOCK INT,
@DESCRIPCION VARCHAR(100),
@CODIGONUEVO INT OUTPUT 
AS
INSERT INTO PRODUCTO(ID_TPROD, ID_PP, NOMBRE, PRECIO_UNITARIO , STOCK, DESCRIPCION) VALUES (@ID_TPROD,@ID_PP,@NOMBRE,@PRECIO_UNI,@STOCK,@DESCRIPCION)
select @CODIGONUEVO  = SCOPE_IDENTITY()
GO

CREATE PROCEDURE SP_REGISTRAR_DETALLE_PRO
@ID_PROD INT ,
@ID_PA INT ,
@ID_LAB INT ,
@NRO_LOTE  VARCHAR(20),
@FECHA_VENCIMIENTO DATETIME ,
@CONDICION_VENTA VARCHAR(45), -- CON RECETA MEDICA // SIN RECETA MEDICA //  CON RECETA MEDICA RETENIDA
@TIPO_MEDICAMENTO VARCHAR(45)  -- GENERICO  // DE MARCA 
AS
INSERT INTO DETALLE_MEDICAMENTO(ID_PROD,ID_PA,ID_LAB,NRO_LOTE,FECHA_VENCIMIENTO,CONDICION_VENTA,TIPO_MEDICAMENTO) VALUES(@ID_PROD,@ID_PA,@ID_LAB,@NRO_LOTE,@FECHA_VENCIMIENTO,@CONDICION_VENTA,@TIPO_MEDICAMENTO)
GO

CREATE PROCEDURE SP_BUSCAR_PRODUCTO
@ID_TPROD INT,
@TEXTO VARCHAR(45)
AS 
SELECT ID_PROD AS CodigoProducto , NOMBRE as NombreProducto , STOCK, PRECIO_UNITARIO  FROM PRODUCTO WHERE ID_TPROD = @ID_TPROD AND   NOMBRE LIKE @TEXTO+'%'; 
GO

CREATE PROCEDURE SP_REGISTRAR_VENTA
@ID_USUARIO INT ,
@CODIGOSALIDA INT OUTPUT
AS
INSERT INTO VENTA(ID_USUARIO) VALUES(@ID_USUARIO);
SELECT @CODIGOSALIDA = SCOPE_IDENTITY()
GO

ALTER PROCEDURE SP_REGISTRAR_DETALLE_VENTA
@ID_VENTA INT ,
@ID_PROD INT  ,
@CANTIDAD INT  ,
@DESCUENTO DECIMAL(10,2) = 0
AS
INSERT INTO DETALLE_VENTA(ID_VENTA,ID_PROD,CANTIDAD,DESCUENTO) VALUES(@ID_VENTA,@ID_PROD,@CANTIDAD,@DESCUENTO)
UPDATE PRODUCTO SET STOCK -=@CANTIDAD  WHERE ID_PROD = @ID_PROD
GO


CREATE PROCEDURE REGISTRAR_USUARIO
@USERNAME VARCHAR(20),
@XPASSWORD VARCHAR(45) ,
@ID_TPUS INT ,
@DESCRIPCION VARCHAR(45),
@CODIGO INT OUTPUT
AS
INSERT INTO USUARIO(USERNAME , XPASSWORD,ID_TPUS,DESCRIPCION) VALUES(@USERNAME,@XPASSWORD,@ID_TPUS,@DESCRIPCION)
SELECT @CODIGO = SCOPE_IDENTITY()
GO

SELECT U.ID_USUARIO as codigo, U.USERNAME as usuario , U.XPASSWORD as password , TU.DESCRIPCION as tipousuario,  U.FECHAALTA as fechaalta   FROM USUARIO U INNER JOIN TIPO_USUARIO TU ON U.ID_TPUS = TU.ID_TPUS


CREATE TABLE PROVEEDOR
(
ID_PROV INT PRIMARY KEY IDENTITY(100,1),
RAZON_SOCIAL VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
ESTADO CHAR(1) DEFAULT 'A'
)

CREATE TABLE PROVEEDOR_PRODUCTO(
ID_PROVP INT PRIMARY KEY IDENTITY(1,1),
ID_PROV INT FOREIGN KEY REFERENCES PROVEEDOR(ID_PROV),
ID_PROD INT FOREIGN KEY REFERENCES PRODUCTO(ID_PROD)
)


CREATE TABLE ORDEN_COMPRA(
ID_ORDENC INT PRIMARY KEY IDENTITY(1,1),
ID_PROVP INT FOREIGN KEY REFERENCES PROVEEDOR_PRODUCTO(ID_PROVP),
MONTO DECIMAL(10,2) NOT NULL,
ARRIVO INT ,
FECHA_ORDEN DATETIME DEFAULT GETDATE(),
ESTADO CHAR(1) DEFAULT 'P'
)
GO



CREATE PROCEDURE USP_NUEVO_PROVEEDOR
@RAZON_SOCIAL VARCHAR(50),
@TELEFONO VARCHAR(50),
@EMAIL VARCHAR(50)
AS
INSERT INTO PROVEEDOR(RAZON_SOCIAL,TELEFONO,EMAIL) VALUES(@RAZON_SOCIAL, @TELEFONO,@EMAIL)
GO


select ID_PROV, RAZON_SOCIAL , TELEFONO,EMAIL from PROVEEDOR
go

CREATE PROCEDURE USP_ASIGNAR_PROD_PROVEEDOR
@ID_PROV INT,
@ID_PROD INT 
AS
INSERT INTO PROVEEDOR_PRODUCTO(ID_PROD, ID_PROV) VALUES(@ID_PROD , @ID_PROV)
GO




/*
byte[] theBytes = Encoding.UTF8.GetBytes(theString);
and later:

string theString = Encoding.UTF8.GetString(theBytes);
*/



CREATE PROCEDURE USP_LISTAR_MEDICAMENTOS
AS
SELECT P.ID_PROD AS CODIGO , P.NOMBRE AS NOMBRE_PRODUCTO , P.STOCK AS STOCK , DM.FECHA_VENCIMIENTO AS VENCE_EL , L.RAZON_SOCIAL AS LABORATORIO , PA.DESCRIPCION AS PRINCIO_ACTIVO FROM PRODUCTO P INNER JOIN DETALLE_MEDICAMENTO  DM ON P.ID_PROD = DM.ID_PROD INNER JOIN LABORATORIO L ON L.ID_LAB = DM.ID_LAB
						INNER JOIN PRINCIPIO_ACTIVO PA ON DM.ID_PA = PA.ID_PA INNER JOIN PRESENTACION_PRODUCTO PP ON P.ID_PP = PP.ID_PP ORDER BY P.STOCK DESC
GO

CREATE PROCEDURE USP_LISTAR_OTROS
AS
SELECT P.ID_PROD AS CODIGO , P.NOMBRE , P.STOCK , PP.DESCRIPCION , TP.DESCRIPCION FROM PRODUCTO P INNER JOIN PRESENTACION_PRODUCTO PP ON P.ID_PP = PP.ID_PP INNER JOIN TIPO_PRODUCTO TP ON TP.ID_TPROD = P.ID_TPROD
		WHERE TP.ID_TPROD != 2 ORDER BY P.STOCK DESC
GO


ALTER PROCEDURE USP_VENTAS
@X VARCHAR(50)
AS
select v.ID_VENTA  CODIGO_VENTA , V.FECHAPEDIDO REALIZADA_EL , U.USERNAME  POR , TU.DESCRIPCION ROL  from VENTA  v inner join USUARIO u on v.ID_USUARIO = u.ID_USUARIO INNER JOIN TIPO_USUARIO TU ON U.ID_TPUS = TU.ID_TPUS WHERE  V.ID_VENTA  LIKE CAST(@X  AS NVARCHAR) + '%' 
GO

ALTER PROCEDURE USP_DETALLE_VENTAS
@X VARCHAR(50)
AS
select dv.ID_DETVENTA AS CODIGODETALLE , V.ID_VENTA AS CODIGO_VENTA , P.NOMBRE PRODUCTO, TP.DESCRIPCION AS TIPO_PRODUCTO from DETALLE_VENTA  dv inner join VENTA v ON dv.ID_VENTA = v.ID_VENTA INNER JOIN PRODUCTO P ON dv.ID_PROD = P.ID_PROD INNER JOIN TIPO_PRODUCTO TP  ON P.ID_TPROD = TP.ID_TPROD WHERE V.ID_VENTA LIKE CAST(@X  AS NVARCHAR) + '%' 
GO

SELECT * FROM USUARIO INNER JOIN TIPO_USUARIO ON USUARIO.ID_TPUS = TIPO_USUARIO.ID_TPUS
SELECT  * FROM TIPO_USUARIO



ALTER  TRIGGER TR_NO_STOCK_PRODUCTOS
ON PRODUCTO AFTER UPDATE
AS
	-- DECLARO LA VARIABLE DEL PAIS
	DECLARE @STOCK INT
	-- ASIGNO A LA VARIAVLE EL CONTENIDO DEL PAIS NUEVO
	SELECT @STOCK = STOCK FROM INSERTED
	-- PREGUNTANDO POR LA REGLA DE NOGOCIO
	IF @STOCK < 0 
	begin
	print 
		'NO EXISTE STOCK SUFICIENTE PARA SATISFACER EL PEDIDO '
		ROLLBACK
	end
GO

SELECT * FROM VENTA


use farmacia2017


select * from INFORMATION_SCHEMA.TABLES
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('SUSPENSION OFTALMICA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('UNGUENTO DERMICO')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('EXTRACTO LIQUIDO')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('SOLUCION ORAL')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('SUSPENSION')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('INYECTABLE')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('LIQUIDO CRIOGENICO')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('SOLUCION OTICA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('SOLUCION NASAL')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('JALEA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('BARRA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('AEROSOL')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('JALEA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('CHAMPU')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('CAPSULA BLANDA')
INSERT INTO PRESENTACION_PRODUCTO(DESCRIPCION ) VALUES ('PARCHE')
SELECT * FROM PRESENTACION_PRODUCTO
GO


SELECT * FROM PRINCIPIO_ACTIVO


INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Abacavir','monofarmaco')                                                                                             
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Abatacept','monofarmaco')
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Abciximab','monofarmaco')                                                                                            
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Abies sibirica Ledeb.essential oil','monofarmaco')
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Aceclofenaco','monofarmaco')                                                                                         
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acemetacina','monofarmaco')                                                                                          
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acenocumarol','monofarmaco')                                                                                         
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('ACETATO DE ABIRATERONA','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acetato de sodio','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acetazolamida','monofarmaco')                                                                                        
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acetilcarnitina','monofarmaco')                                                                                      
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('ACETILCISTEÍNA','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('ACETILCISTEÍNA','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Aciclovir','monofarmaco')                                                                            
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido acético','monofarmaco')                                                                                        
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido acetilsalicílico','monofarmaco')                                                               
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido acetilsalicílico, combinaciones excl. psicolépticos','monofarmaco')                                            
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido alendrónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido alendrónico y colecalciferol','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido alendrónico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido algínico','monofarmaco')                                                                                       
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ascórbico (vit C)','monofarmaco')                                                                              
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ascórbico (vitamina C), monodroga','monofarmaco')                                                              
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido azelaico','monofarmaco')                                                                                       
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido clodrónico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido cromoglícico','monofarmaco')                                                                                   
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido cromoglícico','monofarmaco')                                                                                   
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido flufenAmico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido fólico','monofarmaco')                                                                                         
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido fólico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido fusídico','monofarmaco')                                                                                       
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido fusídico','monofarmaco')                                                                                       
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido gadopentético','monofarmaco')                                                                                  
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido gadotérico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido gadoxético','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido hialurónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido hialurónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido hialurónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido hialurónico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ibandrónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido iotalAmico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ioxAglico','monofarmaco')                                                                                      
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ioxitalAmico','monofarmaco')                                                                                   
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido lActico','monofarmaco')          
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido mefenAmico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido micofenólico','monofarmaco')                                                                                   
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido nalidíxico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido nicotínico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido pamidrónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido pipemídico','monofarmaco')                                                                                     
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido pipemídico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido Salicílico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido tióctico','monofarmaco')                                                                                       
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido tranexAmico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido undecilénico','monofarmaco')                                                                                   
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido undecilénico, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido ursodeoxicólico','monofarmaco')                                                                                
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido valproico','monofarmaco')                                                                                      
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acido zoledrónico','monofarmaco')                                                                                    
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Acitretina','monofarmaco')                                                                                           
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Adapaleno','monofarmaco')                                                                                          
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Adapaleno, combinaciones','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Adenosina','monofarmaco')                                                                                            
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Agalsidasa alfa','monofarmaco')                                                                                      
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Agalsidasa beta','monofarmaco')                                                                                      
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('AGENTES ANTITROMBÓTICOS','monofarmaco')                                                                              
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Agentes inmunosupresores selectivos','monofarmaco')                                                                  
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Agentes quelantes del hierro','monofarmaco')                                                                         
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('AGENTES SOLVENTES Y DILUYENTES, INCL. SOLUCIONES PARA IRRIGACIÓN','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Agomelatina','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('ALANILGLUTAMINA','monofarmaco') 
INSERT INTO PRINCIPIO_ACTIVO(DESCRIPCION,CATEGORIA) VALUES ('Albendazol','monofarmaco')
GO

ALTER PROC USP_DETALLE_VENTABOLETA
@CODIGO INT
AS
select dv.ID_DETVENTA  as ID_DETVENTA , V.ID_VENTA as  ID_VENTA,   P.NOMBRE  as NOMBRE, P.PRECIO_UNITARIO  PRECIO_UNITARIO , dv.CANTIDAD   CANTIDAD from DETALLE_VENTA  dv INNER join VENTA v ON dv.ID_VENTA = v.ID_VENTA INNER JOIN PRODUCTO P ON dv.ID_PROD = P.ID_PROD WHERE V.ID_VENTA = @CODIGO
GO

SELECT * FROM DETALLE_VENTA
GO

EXEC USP_DETALLE_VENTABOLETA 8
GO


ALTER PROC USP_DETALLE_PROD
@FECHAINI VARCHAR(45) = NULL ,
@FECHAFIN VARCHAR(45) = NULL,
@TIPO_PRODUCTO INT = NULL,
@TIPO_PRESENTACION INT = NULL
AS
select P.NOMBRE producto , COUNT(*) ventas , SUM(DT.CANTIDAD) total_Vendido , MIN(V.FECHAPEDIDO) DESDE , MAX(V.FECHAPEDIDO) HASTA from DETALLE_VENTA DT INNER JOIN VENTA V ON DT.ID_VENTA = V.ID_VENTA INNER JOIN PRODUCTO P ON DT.ID_PROD = P.ID_PROD
where (@FECHAINI IS NULL OR V.FECHAPEDIDO BETWEEN @FECHAINI AND @FECHAFIN) AND (@TIPO_PRODUCTO IS NULL OR P.ID_TPROD = @TIPO_PRODUCTO ) AND (@TIPO_PRESENTACION IS NULL  OR P.ID_PP = @TIPO_PRESENTACION)
GROUP BY P.NOMBRE


/*numero de productos*/
GO

EXEC USP_DETALLE_PROD '01-01-2014' , '01-01-2018'




SELECT * FROM TIPO_PRODUCTO
SELECT * FROM PRESENTACION_PRODUCTO
GO

ALTER PROC USP_FILTRAR_VENTA_FECHAS
@FECHAINI DATE = NULL,
@FECHAFIN DATE = NULL
AS
SELECT v.ID_VENTA Codigo_Venta, U.USERNAME  Cajero , COUNT(dt.ID_DETVENTA) Productos , SUM(dt.CANTIDAD * P.PRECIO_UNITARIO) TotalVenta  FROM VENTA v inner join DETALLE_VENTA dt on v.ID_VENTA = dt.ID_VENTA  INNER JOIN PRODUCTO P ON dt.ID_PROD  = P.ID_PROD INNER JOIN USUARIO U ON V.ID_USUARIO = U.ID_USUARIO WHERE ( @FECHAINI IS NULL OR @FECHAFIN IS NULL OR v.FECHAPEDIDO BETWEEN @FECHAINI AND @FECHAFIN)
GROUP BY V.ID_VENTA , U.USERNAME
GO

EXEC USP_FILTRAR_VENTA_FECHAS 


SELECT * FROM VENTA

SELECT * FROM USUARIO

select * from TIPO_PRODUCTO
select * from PRODUCTO

SELECT * FROM DETALLE_MEDICAMENTO WHERE ID_PROD = 105
